#!/bin/bash
docker run --name Abathur -v ~/bonsoir:/root -p 3000:3000 -dit python:2-slim
docker exec Abathur pip install flask
echo 'from flask import Flask\napp = Flask(__name__)\n@app.route("/")\ndef hello():\n\treturn "<h1>hello world!</h1>"' > ~/bonsoir/main.py && chmod 777 ~/bonsoir/main.py
docker exec --env FLASK_APP=/root/main.py Abathur flask run --host=0.0.0.0 --port=3000
